import type {
  AgentIdentity,
  AgentMessage,
  AgentPermissions,
  AgentSession,
  ClyDevTaskIdentity,
  NewAgentSessionInput,
  WorkbenchTab,
} from "./types";

const taskIdentity = ({
  title,
  branch,
  worktree,
  model = "gpt-5.6-sol",
  reasoningLevel = "high",
  usedTokens = 58_200,
  usedCostMinorUnits = 284,
  researchImpact = "Changes the discordance definition linked to the primary claim.",
  researchObjectIds = ["claim-01", "exp-01", "code-01"],
  risk = "medium",
}: {
  title: string;
  branch: string;
  worktree?: string;
  model?: string;
  reasoningLevel?: ClyDevTaskIdentity["provider"]["reasoningLevel"];
  usedTokens?: number;
  usedCostMinorUnits?: number;
  researchImpact?: string;
  researchObjectIds?: string[];
  risk?: ClyDevTaskIdentity["researchImpact"]["risk"];
}): ClyDevTaskIdentity => ({
  project: { id: "project-cly", name: "When LDL-C misleads" },
  repository: {
    name: "ldl-apob-discordance",
    remote: "github.com/cly-labs/ldl-apob-discordance",
  },
  workspace: { branch, worktree, commit: "6e82a1f" },
  machine: { id: "machine-local", name: "Research Mac" },
  provider: {
    id: "openai",
    model,
    reasoningLevel,
  },
  budget: {
    usedTokens,
    maxTokens: 200_000,
    usedCostMinorUnits,
    maxCostMinorUnits: 1_000,
  },
  objective: { title, issueId: "CLY-74" },
  researchImpact: {
    summary: researchImpact,
    objectIds: researchObjectIds,
    risk,
  },
});

const standardPermissions: AgentPermissions = {
  canReadFiles: true,
  canWriteFiles: true,
  canRunCommands: true,
  canAccessNetwork: false,
  requiresApprovalForWrite: true,
  requiresApprovalForNetwork: true,
};

const readOnlyPermissions: AgentPermissions = {
  ...standardPermissions,
  canWriteFiles: false,
  requiresApprovalForWrite: false,
};

const agent = (
  patch: Partial<AgentIdentity> &
    Pick<AgentIdentity, "id" | "name" | "role" | "roleLabel" | "task">,
): AgentIdentity => ({
  provider: "openai",
  model: "gpt-5.6-sol",
  reasoningLevel: "High",
  contextPackId: "pack-claim",
  contextPackName: "Claim Audit Pack",
  contextMode: "task_scoped",
  permissions: standardPermissions,
  tools: ["Files", "Terminal", "Git", "Research graph"],
  worktree: ".cly-worktrees/claim-audit",
  status: "working",
  progress: 52,
  lastAction: "Reading linked evidence",
  currentResource: "analysis/discordance.py",
  usage: "31.4k tokens · $1.42 estimate",
  elapsed: "18m 42s",
  approvalPolicy: "Approve writes and network",
  maximumRuntime: "2 hours",
  fallbackModel: "gpt-5.4-mini",
  reportingDestination: "Orchestrator",
  transcript: [
    "Mapped the current objective to three linked claims.",
    "Inspecting implementation and evidence provenance.",
  ],
  ...patch,
});

export const workbenchFixtureTabs = (): WorkbenchTab[] => [
  {
    id: "tab-agents",
    type: "agents",
    title: "Agents",
    pinned: true,
    state: { view: "tiled" },
  },
  {
    id: "tab-terminal",
    type: "terminal",
    title: "Tests",
    pinned: false,
    state: {
      process: "pnpm test",
      cwd: "~/research/ldl-apob-discordance",
      status: "running",
      lines: [
        "$ python -m pytest tests/analysis",
        "✓ test_discordance.py (12 tests) 184ms",
        "✓ test_model.py (9 tests) 92ms",
        "⠋ reviewer is checking the threshold sensitivity…",
      ],
    },
  },
  {
    id: "tab-browser",
    type: "browser",
    title: "ApoB paper",
    pinned: false,
    state: {
      url: "https://doi.org/10.1001/jamacardio.2024.1310",
      pageTitle: "Individual variation in ApoB across LDL-C levels",
      pageType: "paper",
      sourceAdded: false,
    },
  },
  {
    id: "tab-diff",
    type: "diff",
    title: "Code Diff",
    pinned: false,
    state: {
      selectedPath: "analysis/discordance.py",
      layout: "unified",
      reviewState: "pending",
      files: [
        {
          path: "analysis/discordance.py",
          status: "modified",
          additions: 18,
          deletions: 6,
          staged: false,
          agentId: "agent-implementation",
          risk: "Medium · changes the primary outcome definition",
          diff: [
            "@@ -71,7 +71,12 @@ def discordantly_high_apob(frame):",
            "-    return frame.apob_percentile > frame.ldl_percentile",
            "+    gap = frame.apob_percentile - frame.ldl_percentile",
            "+    # Keep the preregistered 20-point threshold explicit.",
            "+    outcome = gap >= 0.20",
            "+    assert outcome.notna().all()",
            "+    return outcome",
          ],
        },
        {
          path: "tests/analysis/test_discordance.py",
          status: "added",
          additions: 42,
          deletions: 0,
          staged: false,
          agentId: "agent-implementation",
          risk: "Low · outcome regression coverage only",
          diff: [
            "@@ -0,0 +1,4 @@",
            "+def test_twenty_point_gap_is_inclusive():",
            "+    row = percentiles(ldl=0.40, apob=0.60)",
            "+    assert discordantly_high_apob(row)",
            "+    assert not discordantly_high_apob(percentiles(0.40, 0.59))",
          ],
        },
      ],
    },
  },
  {
    id: "tab-live-files",
    type: "live-files",
    title: "Live Files",
    pinned: false,
    state: {
      selectedPath: "analysis/discordance.py",
      followAgent: true,
      autoScroll: true,
      diffOverlay: true,
      edits: [
        {
          id: "edit-01",
          filePath: "analysis/discordance.py",
          agentId: "agent-implementation",
          startedAt: "4 seconds ago",
          changedRanges: [{ startLine: 142, endLine: 176 }],
          summary: "Making the discordance threshold explicit and testable",
        },
        {
          id: "edit-02",
          filePath: "tests/analysis/test_discordance.py",
          agentId: "agent-reviewer",
          startedAt: "22 seconds ago",
          changedRanges: [{ startLine: 18, endLine: 41 }],
          summary: "Adding boundary cases for the 20-point gap",
        },
      ],
    },
  },
];

const activeMessages: AgentMessage[] = [
  {
    id: "message-01",
    type: "system",
    author: "Cly",
    title: "Session started",
    body: "Claim Audit Pack attached · write and network actions require approval.",
    timestamp: "08:12",
  },
  {
    id: "message-02",
    type: "user",
    author: "You",
    body: "Audit the main finding. Trace the CDC data through the model and tell me what we can responsibly claim about LDL-C discordance.",
    timestamp: "08:13",
  },
  {
    id: "message-03",
    type: "orchestrator",
    author: "Cly Orchestrator",
    body: "I’ll trace the claim from the six CDC files through cohort selection, target definition, validation, and exported results. I’m delegating a methods audit and an independent clinical-language review, then I’ll reconcile both against the source evidence.",
    timestamp: "08:13",
    metadata: ["GPT-5.6 Sol", "High reasoning", "Claim Audit Pack"],
  },
  {
    id: "message-04",
    type: "delegation",
    author: "Codex Implementation Agent",
    agentId: "agent-implementation",
    title: "Implementation review delegated",
    body: "Reviewing analysis/discordance.py and tracing the 20-percentile definition into the primary claim.",
    timestamp: "08:14",
    metadata: ["GPT-5.6 Sol", "High reasoning", "Working"],
    actions: ["Open agent", "View task", "Steer"],
  },
  {
    id: "message-05",
    type: "tool_result",
    author: "Cly Orchestrator",
    title: "Evidence trace · 13 linked objects",
    body: "4 sources · 2 claims · 2 experiments · 2 runs · 2 notebooks · 1 table",
    timestamp: "08:15",
    collapsed: true,
  },
  {
    id: "message-06",
    type: "agent_update",
    author: "Reviewer Agent",
    agentId: "agent-reviewer",
    title: "Potential outcome overclaim",
    body: "The code predicts ApoB–LDL-C discordance, but the draft headline can be read as event-risk prediction. I asked the Implementation Agent to keep the target explicit and add a regression test for the 20-point boundary.",
    timestamp: "08:24",
    metadata: ["Reviewing", "72%", "Risk: medium"],
    actions: ["Open agent", "Open diff"],
  },
  {
    id: "message-07",
    type: "artifact",
    author: "Cly Orchestrator",
    title: "Evidence map generated",
    body: "ldl-discordance-evidence-map.md · 21 KB · linked to Claim 01",
    timestamp: "08:27",
    actions: ["Open artifact", "Add to context"],
  },
];

export const createAgentSessionFixtures = (): AgentSession[] => {
  const orchestrator = agent({
    id: "agent-orchestrator",
    name: "Cly Orchestrator",
    role: "orchestrator",
    roleLabel: "Orchestrator",
    task: "Coordinate the discordance audit and synthesize a defensible recommendation",
    progress: 64,
    currentResource: "Claim 01 · Basic health data flag discordance",
    contextMode: "explicit_pack",
  });
  const implementationAgent = agent({
    id: "agent-implementation",
    name: "Codex Implementation Agent",
    role: "implementation",
    roleLabel: "Worker Agent",
    task: "Trace the discordance definition through code and tests",
    provider: "openai",
    model: "gpt-5.6-sol",
    progress: 68,
    lastAction: "Editing discordance.py",
  });
  const reviewerAgent = agent({
    id: "agent-reviewer",
    name: "Reviewer Agent",
    role: "review",
    roleLabel: "Reviewer Agent",
    task: "Independently challenge the implementation and evidence chain",
    provider: "anthropic",
    model: "opus",
    status: "reviewing",
    progress: 72,
    lastAction: "Reviewing new regression test",
    currentResource: "tests/analysis/test_discordance.py",
    permissions: readOnlyPermissions,
    worktree: ".cly-worktrees/claim-review",
  });

  return [
    {
      id: "session-01",
      projectId: "project-cly",
      title: "Audit LDL-C discordance evidence",
      objective:
        "Trace the LDL-C discordance claim through CDC source files, cohort rules, code, validation, and artifacts; identify the smallest defensible correction.",
      identity: taskIdentity({
        title: "Audit LDL-C discordance evidence",
        branch: "agent/discordance-audit",
        worktree: ".cly-worktrees/claim-audit",
      }),
      workspaceMode: "inline-workspace",
      taskState: "streaming",
      orchestrator,
      delegatedAgents: [implementationAgent, reviewerAgent],
      tasks: [
        {
          id: "task-implementation",
          parentSessionId: "session-01",
          assignedAgentId: implementationAgent.id,
          title: "Implementation trace",
          objective:
            "Verify the percentile-gap implementation against the registered method",
          status: "working",
          progress: 68,
          dependencies: [],
          artifacts: ["discordance.patch", "regression-test.txt"],
        },
        {
          id: "task-review",
          parentSessionId: "session-01",
          assignedAgentId: reviewerAgent.id,
          title: "Independent review",
          objective:
            "Challenge the fix and identify unsupported claim language",
          status: "reviewing",
          progress: 72,
          dependencies: ["task-implementation"],
          artifacts: ["review-notes.md"],
        },
      ],
      status: "running",
      progress: 64,
      startedAt: "Today, 08:12",
      updatedAt: "Just now",
      elapsed: "18m 42s",
      activeContextPackId: "pack-claim",
      activeContextPackName: "Claim Audit Pack",
      contextSummary: "11 objects · 28.7k tokens · 3 pinned",
      preset: "Claim Audit",
      branch: "agent/discordance-audit",
      worktree: ".cly-worktrees/claim-audit",
      messages: activeMessages,
      workbenchTabs: workbenchFixtureTabs(),
      activeWorkbenchTabId: "tab-agents",
      workbenchCollapsed: false,
      workbenchMaximized: false,
      workbenchWidth: 40,
      draft: "",
      usageEstimate: "$2.84 · 58.2k tokens",
      connectionState: "connected",
      approvals: [],
      artifacts: ["Evidence map", "Review notes", "Discordance patch"],
      relatedResearchObject: "Claim 01 · Basic data flag discordance",
      risk: "Medium · headline may overstate the outcome",
      archived: false,
    },
    {
      id: "session-02",
      projectId: "project-cly",
      title: "Plan external validation",
      objective:
        "Prepare a later-cycle validation experiment with explicit cohort rules and acceptance criteria.",
      identity: taskIdentity({
        title: "Plan external validation",
        branch: "experiment/external-validation",
        usedTokens: 21_800,
        usedCostMinorUnits: 92,
        researchImpact:
          "May change the evidence supporting the primary discordance claim.",
        researchObjectIds: ["claim-01", "exp-04"],
        risk: "high",
      }),
      workspaceMode: "inline-workspace",
      taskState: "awaiting-approval",
      orchestrator: agent({
        id: "agent-plan-orchestrator",
        name: "Experiment Orchestrator",
        role: "orchestrator",
        roleLabel: "Orchestrator",
        task: "Build an approval-ready experiment plan",
        status: "waiting_approval",
        progress: 38,
        contextPackName: "Experiment Planning Pack",
      }),
      delegatedAgents: [
        agent({
          id: "agent-analysis",
          name: "Analysis Agent",
          role: "analysis",
          roleLabel: "Analysis Agent",
          task: "Estimate cohort size and validation precision",
          status: "waiting_approval",
          progress: 44,
          contextPackName: "Experiment Planning Pack",
          permissions: readOnlyPermissions,
        }),
      ],
      tasks: [],
      status: "waiting_approval",
      progress: 38,
      startedAt: "Yesterday, 16:40",
      updatedAt: "12m ago",
      elapsed: "1h 08m",
      activeContextPackId: "pack-experiment",
      activeContextPackName: "Experiment Planning Pack",
      contextSummary: "8 objects · 19.1k tokens · 2 pinned",
      preset: "Experiment Planning",
      branch: "experiment/external-validation",
      messages: [
        ...activeMessages.slice(0, 3),
        {
          id: "message-approval",
          type: "approval",
          author: "Experiment Orchestrator",
          title: "Approval required · download later cycles",
          body: "The validation requires additional CDC files. Expected output: a temporally separated comparison linked to the primary discordance claim.",
          timestamp: "Yesterday, 17:28",
          status: "pending",
          actions: ["Approve", "Edit constraints", "Reject"],
        },
      ],
      workbenchTabs: workbenchFixtureTabs().slice(0, 3),
      activeWorkbenchTabId: "tab-agents",
      workbenchCollapsed: false,
      workbenchMaximized: false,
      workbenchWidth: 38,
      draft: "",
      usageEstimate: "$0.92 · 21.8k tokens",
      connectionState: "connected",
      approvals: [
        {
          id: "approval-compute",
          title: "Download later NHANES cycles",
          detail:
            "Agent requests network permission to fetch official CDC files.",
          estimate: "18 public-use files",
          expectedOutput: "Temporal validation report",
          affectedObject: "Primary discordance claim",
          state: "pending",
        },
      ],
      artifacts: ["Draft configuration", "Budget estimate"],
      relatedResearchObject: "Experiment 04 · External validation",
      risk: "Approval blocking one delegated agent",
      archived: false,
    },
    {
      id: "session-03",
      projectId: "project-cly",
      title: "Review prediction notebook",
      objective:
        "Find hidden state, survey-design gaps, and provenance breaks in the prediction notebook.",
      identity: taskIdentity({
        title: "Review prediction notebook",
        branch: "audit/prediction-notebook",
        usedTokens: 18_300,
        usedCostMinorUnits: 74,
        researchImpact:
          "Documents reproducibility gaps without changing research objects.",
        researchObjectIds: ["nb-02"],
        risk: "low",
      }),
      workspaceMode: "agent-only",
      taskState: "interrupted-resumable",
      orchestrator: agent({
        id: "agent-notebook-orchestrator",
        name: "Notebook Review Orchestrator",
        role: "orchestrator",
        roleLabel: "Orchestrator",
        task: "Summarize the completed notebook audit",
        status: "completed",
        progress: 100,
        contextPackName: "Notebook Cleanup",
      }),
      delegatedAgents: [],
      tasks: [],
      status: "completed",
      progress: 100,
      startedAt: "Jul 10, 13:04",
      updatedAt: "Jul 10",
      elapsed: "22m 06s",
      activeContextPackName: "Notebook Cleanup",
      contextSummary: "9 objects · 16.4k tokens · 4 pinned",
      preset: "Notebook Cleanup",
      branch: "audit/prediction-notebook",
      messages: [
        ...activeMessages.slice(0, 3),
        {
          id: "message-complete",
          type: "orchestrator",
          author: "Notebook Review Orchestrator",
          title: "Review complete",
          body: "The notebook is deterministic and hash-linked. Two research gaps remain: survey-design uncertainty is not estimated and external validation is not yet available.",
          timestamp: "Jul 10, 13:26",
          actions: ["Open findings", "Inspect outputs"],
        },
      ],
      workbenchTabs: workbenchFixtureTabs().filter((tab) =>
        ["diff", "live-files"].includes(tab.type),
      ),
      activeWorkbenchTabId: "tab-diff",
      workbenchCollapsed: false,
      workbenchMaximized: false,
      workbenchWidth: 40,
      draft: "",
      usageEstimate: "$0.74 · 18.3k tokens",
      connectionState: "offline",
      approvals: [],
      artifacts: ["2 findings", "Validation plan", "Context pack"],
      relatedResearchObject: "Notebook · 02-prediction-benchmark.ipynb",
      archived: false,
    },
  ];
};

export const createNewAgentSession = (
  input: NewAgentSessionInput,
  id = `session-${Date.now()}`,
): AgentSession => {
  const orchestrator = agent({
    id: `${id}-orchestrator`,
    name: "Cly Orchestrator",
    role: "orchestrator",
    roleLabel: "Orchestrator",
    task: input.objective,
    provider: input.provider,
    model: input.model,
    reasoningLevel: input.reasoningLevel,
    contextPackName: input.contextPackName,
    contextMode: "explicit_pack",
    progress: 4,
    lastAction: "Preparing task plan",
    currentResource: input.objective,
    approvalPolicy: input.approvalPolicy,
    usage: `Budget ${input.usageBudget}`,
  });
  const implementationAgent = agent({
    id: `${id}-implementation`,
    name: "Codex Implementation Agent",
    role: "implementation",
    roleLabel: "Worker Agent",
    task: "Inspect the implementation and prepare scoped changes",
    provider: input.provider,
    model: input.model,
    reasoningLevel: input.reasoningLevel,
    contextPackName: input.contextPackName,
    status: "starting",
    progress: 2,
    lastAction: "Starting independent agent session",
    currentResource: input.branchPreference,
  });
  const reviewerAgent = agent({
    id: `${id}-reviewer`,
    name: "Reviewer Agent",
    role: "review",
    roleLabel: "Reviewer Agent",
    task: "Review the plan, evidence, and implementation independently",
    provider: input.provider,
    model: input.model,
    reasoningLevel: input.reasoningLevel,
    contextPackName: input.contextPackName,
    status: "queued",
    progress: 0,
    lastAction: "Waiting for the Orchestrator task packet",
    permissions: readOnlyPermissions,
  });
  return {
    id,
    projectId: "project-cly",
    title: input.title,
    objective: input.objective,
    identity: taskIdentity({
      title: input.title,
      branch: input.branchPreference,
      model: input.model,
      reasoningLevel:
        input.reasoningLevel === "Extra High"
          ? "xhigh"
          : (input.reasoningLevel.toLowerCase() as ClyDevTaskIdentity["provider"]["reasoningLevel"]),
      usedTokens: 0,
      usedCostMinorUnits: 0,
      researchImpact: "Research impact has not been assessed yet.",
      researchObjectIds: [],
      risk: "low",
    }),
    workspaceMode: "inline-workspace",
    taskState: "loading",
    orchestrator,
    delegatedAgents: [implementationAgent, reviewerAgent],
    tasks: [
      {
        id: `${id}-implementation-task`,
        parentSessionId: id,
        assignedAgentId: implementationAgent.id,
        title: "Implementation investigation",
        objective: input.objective,
        status: "starting",
        progress: 2,
        dependencies: [],
        artifacts: [],
      },
      {
        id: `${id}-review-task`,
        parentSessionId: id,
        assignedAgentId: reviewerAgent.id,
        title: "Independent review",
        objective: `Challenge the evidence and proposed work for: ${input.objective}`,
        status: "queued",
        progress: 0,
        dependencies: [`${id}-implementation-task`],
        artifacts: [],
      },
    ],
    status: "running",
    progress: 4,
    startedAt: "Just now",
    updatedAt: "Just now",
    elapsed: "00m 02s",
    activeContextPackName: input.contextPackName,
    contextSummary: "Context preparing · 3 pinned",
    preset: input.preset,
    branch: input.branchPreference,
    messages: [
      {
        id: `${id}-system`,
        type: "system",
        author: "Cly",
        title: "Session started",
        body: `${input.contextPackName} attached · ${input.approvalPolicy}.`,
        timestamp: "Just now",
      },
      {
        id: `${id}-orchestrator-start`,
        type: "reasoning",
        author: "Cly Orchestrator",
        title: "Preparing a research-aware plan",
        body: "Mapping the session goal to the selected context and agent-team preset.",
        timestamp: "Just now",
      },
    ],
    workbenchTabs: workbenchFixtureTabs(),
    activeWorkbenchTabId: "tab-agents",
    workbenchCollapsed: false,
    workbenchMaximized: false,
    workbenchWidth: 40,
    draft: "",
    usageEstimate: `$0.01 · budget ${input.usageBudget}`,
    connectionState: "connected",
    approvals: [],
    artifacts: [],
    relatedResearchObject: "New research task",
    archived: false,
  };
};
