import hashlib
from collections.abc import Mapping, Sequence
from typing import Any

from app.models.ai_providers import (
    ProviderCapabilities,
    ProviderHealth,
    ProviderInfo,
)
from app.services.ai_providers.base import BaseAIProvider


class MockProvider(BaseAIProvider):
    name = "mock"

    def info(self) -> ProviderInfo:
        return ProviderInfo(
            name=self.name,
            provider_type="mock",
            display_name="Mock Provider",
            capabilities=ProviderCapabilities(
                supports_text_generation=True,
                supports_json_generation=True,
                supports_embeddings=True,
                supports_reranking=True,
            ),
            enabled=True,
            is_local=True,
            sends_data_off_machine=False,
        )

    def health_check(self) -> ProviderHealth:
        return ProviderHealth(
            provider_name=self.name,
            available=True,
            status="available",
            message="Mock provider is available and does not call an external model.",
        )

    def generate_text(
        self,
        prompt: str,
        options: Mapping[str, Any] | None = None,
    ) -> str:
        return (
            "Mock provider response. "
            f"Received a prompt with {len(prompt.strip())} characters."
        )

    def generate_json(
        self,
        prompt: str,
        schema: Mapping[str, Any],
        options: Mapping[str, Any] | None = None,
    ) -> Mapping[str, Any]:
        if (options or {}).get("task") == "paper_extraction":
            uses_full_text = "Parsed PDF sections:" in prompt
            return {
                "problem": "Identify the main research problem from title and abstract metadata.",
                "method": (
                    "Mock extraction based on parsed full text sections."
                    if uses_full_text
                    else "Mock extraction based on title and abstract only."
                ),
                "datasets_or_setting": "Not specified by mock provider.",
                "key_results": [
                    "Mock provider does not evaluate empirical results.",
                ],
                "main_contribution": "Deterministic structured note for pipeline development.",
                "limitations": [
                    "This is mock output and should not be treated as paper understanding.",
                ],
                "tags": ["mock", "full-text" if uses_full_text else "abstract-only"],
                "confidence": 1.0,
                "source_quote_or_evidence": "Generated by mock provider from supplied metadata.",
            }

        if (options or {}).get("task") == "landscape_synthesis":
            return {
                "overview": "Mock landscape synthesized from structured paper notes.",
                "clusters": [
                    "Retrieval and tool-selection methods",
                    "Evaluation and benchmark design",
                ],
                "relationships": [
                    "Ranking results feed paper-level extraction, which feeds synthesis.",
                ],
                "tensions": [
                    "Mock synthesis cannot resolve real methodological disagreements.",
                ],
                "open_problems": [
                    "Replace mock output with a configured local model for real synthesis.",
                ],
                "recommended_reading_path": [
                    "Start with the highest-ranked paper, then compare extracted limitations.",
                ],
            }

        return {
            "provider": self.name,
            "summary": "Mock structured response.",
            "prompt_character_count": len(prompt.strip()),
            "confidence": 1.0,
        }

    def embed_texts(
        self,
        texts: Sequence[str],
        options: Mapping[str, Any] | None = None,
    ) -> list[list[float]]:
        return [_hash_embedding(text) for text in texts]

    def rerank(
        self,
        query: str,
        documents: Sequence[str],
        options: Mapping[str, Any] | None = None,
    ) -> list[int]:
        query_terms = set(query.lower().split())
        scores = [
            (index, len(query_terms.intersection(document.lower().split())))
            for index, document in enumerate(documents)
        ]
        scores.sort(key=lambda item: (-item[1], item[0]))
        return [index for index, _score in scores]


def _hash_embedding(text: str) -> list[float]:
    digest = hashlib.sha256(text.encode("utf-8")).digest()
    return [round(byte / 255, 6) for byte in digest[:8]]
